dat <- c("Acute Oral Toxicity Assay",
         "Oral Acute Toxicity",
         "Malformation",
         "Vascularization",
         "Apoptosis",
         "Cell Cycle",
         "Cell Proliferation",
         "Cell Viability",
         "Extracellular Matrix Degradation",
         "Cell Morphology",
         "DNA Damage",
         "Oxidative Stress",
         "p53 Modulation",
         "Aromatase Activity Modulation",
         "Androgen Biosynthesis and Metabolism",
         "Cholesterol Transport",
         "Estrogen Biosynthesis and Metabolism",
         "Glucocorticoid Biosynthesis and Metabolism",
         "Progestogen Biosynthesis and Metabolism",
         "Thyroid Receptor Modulation",
         "Thyrotropin-Releasing Hormone Receptor Modulation",
         "Thyroid Hormone Biosynthesis",
         "Sodium/Iodide Cotransporter",
         "\"Deiodinase",
         "Iodothyronine\"",
         "\"Deiodinase",
         "Iodotyrosine\"",
         "Thyroid Hormone Binding",
         "Mitochondrial Function",
         "Glucagon Receptor Activity Modulation",
         "Bile Acid Mediated Energy Homeostasis",
         "Metabolic Regulation of Insulin Secretion",
         "Histone Modification",
         "Protein Deacetylation",
         "Folate Metabolism",
         "Other Developmental Signaling Transcription Factors",
         "Retinoic Acid Receptor Modulation",
         "Retinoid X Receptor Modulation",
         "Other Fatty Acid Signaling",
         "Peroxisome Proliferator Activated Receptor Modulation",
         "Other Transcription Factors",
         "RAR-related Orphan Receptor Modulation",
         "Estrogen-related Receptor Modulation",
         "Estrogen Receptor Modulation",
         "Glucocorticoid Receptor Modulation",
         "Vitamin D Modulation",
         "Androgen Receptor Modulation",
         "Progesterone Receptor Modulation",
         "Mineralocorticoid Receptor Modulation",
         "\"Gene Expression Regulation",
         "Thyroid Receptor Modulation\"",
         "Aryl Hydrocarbon Receptor Modulation",
         "Liver X Receptor Modulation",
         "Constitutive Androstane Receptor Modulation",
         "Other Xenobiotic Response Transcription Factors",
         "Pregnane X Receptor Modulation",
         "Farnesoid X-activated Receptor Modulation",
         "Clotting",
         "Inflammation",
         "Adrenergic Receptor Modulation",
         "Acetylcholinesterase Activity Modulation",
         "Muscarinic Acetylcholine Receptor Modulation",
         "Dopamine Receptor Modulation",
         "Dopamine Transporter Activity Modulation",
         "Adenosine Receptor Modulation",
         "Gamma-aminobutyric Acid Receptor Modulation",
         "Metabotropic Glutamate Receptor Modulation",
         "Glutamate Ion Channel Receptor Modulation",
         "Histamine Receptor Modulation",
         "Ion Channel Activity",
         "Monoamine Oxidase Activity Modulation",
         "Butyrylcholinesterase Activity Modulation",
         "Neurotransmission",
         "Nicotinic Acid Receptor Modulation",
         "Norepinephrine Transporter Modulation",
         "Opioid Receptor Modulation",
         "Serotonin Receptor Modulation",
         "Serotonin Plasma Membrane Transporter Modulation",
         "Cytochrome P450 Activity Modulation",
         "Unannotated",
         "AcuteTox - Cytotoxicity",
         "AcuteTox - Energy Metabolism Process",
         "AcuteTox - Immune and Inflammatory Response",
         "AcuteTox - Neuronal Transmission",
         "AcuteTox - Oxidative Stress",
         "AcuteTox - p53 Signaling Pathway",
         "AcuteTox - Steroid Hormone Metabolism",
         "Androgen - Gene Expression Regulation",
         "Androgen - Steroid Hormone Metabolism",
         "Estrogen - Gene Expression Regulation",
         "Estrogen - Steroid Hormone Metabolism",
         "Thyroid Hormone - Thyroid Hormone Metabolic Process",
         "Thyroid Hormone - Gene Expression Regulation",
         "Other Steroid Hormone - Gene Expression Regulation",
         "Other Steroid Hormone - Steroid Hormone Metabolism",
         "Cancer - KCC2: Genotoxic Effects",
         "Cancer - KCC3: Alteration of DNA Repair/Genomic Stability",
         "Cancer - KCC4: Epigenetic Alterations",
         "Cancer - KCC5: Oxidative Stress",
         "Cancer - KCC6: Chronic Inflammation",
         "Cancer - KCC8: Receptor Mediated Effects",
         "Cancer - KCC10: Cell Proliferation/Death/Energetics",
         "CardioTox - Change in Vasoactivity",
         "CardioTox - Change in Inotropy",
         "CardioTox - Change in Action Potential",
         "CardioTox - Cardiomyocyte/Myocardial Injury",
         "CardioTox - Valvular Injury/Proliferation",
         "CardioTox - Endothelial Injury/Coagulation",
         "DART - Growth and Differentiation",
         "DART - Angiogenic Process",
         "DART - Cell Death Process",
         "DART - Epigenetic Process",
         "DART - Extracellular Matrix",
         "DART - Androgen Receptor Modulation",
         "DART - Aryl Hydrocarbon Receptor Modulation",
         "DART - Estrogen Receptor Modulation",
         "DART - Other Developmental Signaling Transcription Factors",
         "DART - Progesterone Receptor Modulation",
         "DART - Retinoic Acid Receptor Modulation",
         "DART - Retinoid X Receptor Modulation",
         "DART - Vitamin D Modulation",
         "DART - Neuronal Development",
         "DART - Neuronal Transmission",
         "DART - Oxidative Stress",
         "DART - p53 Signaling Pathway",
         "DART - Steroid Hormone Metabolism",
         "Cancer",
         "DART",
         "Cholinesterase",
         "Developmental",
         "Reproductive",
         "Systemic",
         "IARC Carcinogenicity",
         "NTP Carcinogenicity",
         "OPP Carcinogenicity",
         "Report on Carcinogens",
         "NTP Call Dose",
         "In Vivo Genotoxicity",
         "In Vitro Genotoxicity",
         "Rat Acute Oral Toxicity",
         "Rat Acute Inhalation Toxicity",
         "Rat Acute Dermal Toxicity",
         "Rabbit Draize Skin Irritation/Corrosion Test",
         "Rabbit Draize Eye Irritation/Corrosion Test",
         "In Vivo Skin Sensitization Assays",
         "Acute Dermal Toxicity",
         "Acute Inhalation Toxicity",
         "Guinea Pig Maximization/Buehler",
         "Human Predictive Patch Test",
         "Murine Local Lymph Node Assay (LLNA)",
         "DPRA",
         "U-SENS",
         "SENS-IS",
         "mMUSST",
         "LuSens",
         "hCLAT",
         "KeratinoSens",
         "Skin Sensitization",
         "LLNA",
         "Human Potency",
         "Human Repeat Insult Patch Test",
         "Human Maximization Test",
         "Guinea pig maximization/Buehler",
         "Other In Vivo Skin Sensitization Assays",
         "EpiSkin Irritation",
         "EpiDerm Irritation",
         "LabCyte EPI-MODEL24 Irritation",
         "Vitrolife-Skin Irritation",
         "Corrositex",
         "EpiDerm Corrosion",
         "EpiSkin Corrosion",
         "LabCyte Corrosion",
         "SkinEthic Corrosion",
         "Vitrolife-Skin Corrosion",
         "Rabbit Draize Skin Irritation/Corrosion Test",
         "Acute eye irritation/corrosion",
         "Draize eye",
         "Vitrigel",
         "Four-hour Human Patch Test",
         "In Vitro Skin Corrosion Assays",
         "TER Corrosion",
         "In Vivo Eye Irritation/Corrosion",
         "Vitrigel-Eye Irritancy Test",
         "Eye Corrosivity",
         "\"AR Pathway Model",
         "Agonist\"",
         "\"AR Pathway Model",
         "Antagonist\"",
         "AR Binding and Transactivation",
         "AR Transactivation",
         "AR Transactivation-Antagonist",
         "AR Transactivation-Agonist",
         "AR Binding",
         "AR Pathway Model",
         "ER Pathway Model",
         "ER Binding and Transactivation",
         "ER Agonist",
         "ER Transactivation",
         "ER Transactivation-Agonist (STTA Assay)",
         "ER Transactivation-Antagonist (STTA Assay)",
         "TG455",
         "Hershberger Assay",
         "Hershberger-Agonist",
         "Hershberger-Antagonist",
         "\"ER Pathway Model",
         "Agonist\"",
         "\"ER Pathway Model",
         "Antagonist\"",
         "Uterotrophic Assay",
         "\"CATMoS",
         "Acute Oral Toxicity\"",
         "\"CoMPARA",
         "AR Agonist\"",
         "\"CoMPARA",
         "AR Antagonist\"",
         "\"CoMPARA",
         "AR Binding\"",
         "\"CERAPP",
         "ER Agonist\"",
         "\"CERAPP",
         "ER Antagonist\"",
         "\"CERAPP",
         "ER Binding\"",
         "\"CATMoS",
         "Rat Acute Oral Toxicity\"",
         "\"STTA",
         "Agonist\"",
         "\"STTA",
         "Antagonist\"",
         "TG455 Agonist",
         "TG455 Antagonist",
         "\"VM7 Luc",
         "Agonist\"",
         "\"VM7 Luc",
         "Antagonist\"",
         "\"SEEM3",
         "Exposure Predictions\"",
         "Chemical Properties",
         "\"OPERA",
         "Boiling Point\"",
         "\"OPERA",
         "Henry's Law Constant\"",
         "\"OPERA",
         "Octanol-Air Partition Coefficient\"",
         "\"OPERA",
         "Octanol-Water Distribution Coefficient\"",
         "\"OPERA",
         "Octanol-Water Partition Coefficient\"",
         "\"OPERA",
         "Melting Point\"",
         "\"OPERA",
         "Negative Log of Acid Dissociation Constant\"",
         "\"OPERA",
         "Vapor Pressure\"",
         "\"OPERA",
         "Water Solubility\"",
         "Molecular Weight",
         "\"OPERA",
         "Caco-2 Permeability\"",
         "\"OPERA",
         "HPLC Retention Time\"",
         "\"OPERA",
         "Number of Atoms\"",
         "\"OPERA",
         "Number of Heavy Atoms\"",
         "\"OPERA",
         "Number of Carbon Atoms\"",
         "\"OPERA",
         "Number of Oxygen Atoms\"",
         "\"OPERA",
         "Number of Nitrogen Atoms\"",
         "\"OPERA",
         "Number of Aromatic Atoms\"",
         "\"OPERA",
         "Number of Rings\"",
         "\"OPERA",
         "Number of Rings Containing Heteroatoms\"",
         "\"OPERA",
         "Fraction of Sp3 Carbons to Sp2 Carbons\"",
         "\"OPERA",
         "Number of Rotatable Bonds\"",
         "\"OPERA",
         "Number of Hydrogen Bond Acceptors\"",
         "\"OPERA",
         "Number of Hydrogen Bond Donors\"",
         "\"OPERA",
         "Number Failures of the Lipinski's Rule Of 5\"",
         "\"OPERA",
         "Topological Polar Surface Area\"",
         "\"OPERA",
         "Molar Refractivity\"",
         "\"OPERA",
         "Combined Dipolarity/Polarizability\"",
         "\"OPERA",
         "Fish Bioconcentration Factor\"",
         "\"OPERA",
         "OH rate constant for the atmospheric",
         "gas-phase reaction between photochemically produced hydroxyl radicals and organic chemicals\"",
         "\"OPERA",
         "Biodegradation Half-Life for Compounds Containing Only Carbon and Hydrogen\"",
         "\"OPERA",
         "Ready Biodegradability of Organic Chemicals\"",
         "\"OPERA",
         "Whole Body Primary Biotransformation Rate (Half-Life) Constant for Organic Chemicals in Fish\"",
         "\"OPERA",
         "Soil Adsorption Coefficient of Organic Compounds\"",
         "\"OPERA",
         "Human Plasma Fraction Unbound\"",
         "\"OPERA",
         "Human Hepatic Intrinsic Clearance\"",
         "\"httk",
         "Human Plasma Fraction Unbound\"",
         "\"httk",
         "Human Hepatic Intrinsic Clearance\"",
         "\"httk",
         "Rat Plasma Fraction Unbound\"",
         "\"httk",
         "Rat Hepatic Intrinsic Clearance\"")
